### ISSUE TITLE
RuntimeError: stdlib.Generators.observe is not a function

### ISSUE THREAD

**Issue by jamwalla** [observablehq/stdlib#213]
**Describe the bug**
When embedding cells using the Runtime library, following the [example for custom fluid width](https://github.com/observablehq/examples/tree/main/custom-fluid-width), the redefined `width` causes a `RuntimeError: stdlib.Generators.observe is not a function` which is displayed on the embedded page instead of the chart.

**To Reproduce**
1. See https://www.vera.org/covid-19/criminal-justice-city-and-state-spotlights/michigan
2. Scroll to just below "Select a county" and see error:
```
chart = RuntimeError: stdlib.Generators.observe is not a function
update = RuntimeError: stdlib.Generators.observe is not a function
```
3. See https://www.vera.org/code/michigan-jail-population-and-covid.js for the redefined `width`

**Expected behavior**
`chart` cell inherits parent width and resizes with the window.

**Screenshots**
<img width="474" alt="Screen Shot 2021-05-25 at 11 56 59 AM" src="https://user-images.githubusercontent.com/1993708/119529715-5968b600-bd50-11eb-9135-cd375990630e.png">

**Comment by mbostock** [comment]
This was broken in https://github.com/observablehq/stdlib/pull/207. You can fix this by pinning the runtime version to 4.8.2 (the first broken version is 4.9.0).

```js
import {
  Runtime,
  Inspector,
  Library,
} from "https://cdn.jsdelivr.net/npm/@observablehq/runtime@4.8.2/dist/runtime.js";
```

That example is using an internal API that we inadvertently changed. I’ll see if we can push a patch that restores backwards compatibility, and update that example to use a public API.

**Comment by jamwalla** [comment]
Pinning to 4.8.2 did the trick. Thank you for the very quick fixes!
